### ISSUE TITLE
Mapbox: Credit card information requested

### ISSUE THREAD

**Issue by eronraines** [16EAGLE/basemaps#14]
In order to use the basemap package, one is advised to register at https://www.mapbox.com/. Upon registering, credit card information is requested in order to proceed. When did R become anything less than open-source? When did it become acceptable to market your product using R?

**Comment by 16EAGLE** [comment]
You are free to choose at which map service you register. I am not affiliated with any map service that this package can communicate with. `basemaps` supports multiple map services, some non-commercial, others commercial. I am not advertising anything, I am an independent developer who created a package to make it simpler to use these map services. 

 `basemaps` is fully open source and complies with CRAN policy. I am providing my code for free because I like open source and free software development.

If you choose to become a customer of mapbox that is your choice, not mine. `basemaps` supports various free and open source maps, instead – your choice.

Apart from that, I have been using mapbox's free quota without ever giving them my credit card infos.

**Comment by eronraines** [comment]
I clearly didn't fully understand the situation. I would encourage you to delete this issue chain if you felt so inclined. You have graciously addressed my 'qualms' - which, as it turns out, aren't immediately related to the intentions behind the code you've generously provided. Rather, the qualms are specific to some of the services that the code relies on to function... 

Perhaps it was only recently that mapbox has been requiring credit card information to register. I cannot get around this so I found alternatives. This means I won't be using the code you've provided - which, aside from linking to a service that requires credit card information, is excellent by the way (and the tutorials very generous)...

On a last note, (as you know) there are other data providers for 'realistic' basemaps (like those behind the credit card requirement wall your package queries). For instance, EarthExplorer has Landsat-8 RGB data that can be called and processed for basemaps directly in R. Implementing such a utilitity would certainly add more time to map generation and require more user input but it doesn't require a credit card entry to obtain... I have written code that returns such a basemap and have some code that queries the data. I am sure you are incredibly busy but if you ever thought you might like to extend Mapbox's capabilities to include data never at cost, then I'd be happy to send that code along if you thought it might be helpful.

**Comment by 16EAGLE** [comment]
> Perhaps it was only recently that mapbox has been requiring credit card information to register. I cannot get around this 

Interesting, maybe this depends on ones location from where a mapbox account is created. Do you want to share from where (country) you tried to create an account?

I just tested this from Germany by creating a new account. After entering name, email address, username and password and confirming my email address, I got access to token creation and the APIs without having entered any credit card info. See screenshots below;

![mapbox_registration_01](https://user-images.githubusercontent.com/23257860/205625705-fb61a977-88d4-4d49-acde-360626e898de.png)

![mapbox_registration_02](https://user-images.githubusercontent.com/23257860/205625729-fd605c69-9135-4411-b182-01daa9cb72e5.png)


> For instance, EarthExplorer has Landsat-8 RGB data that can be called and processed for basemaps directly in R

This is indeed very interesting. I experimented with coregistering Landsat and Sentinel previews a bit (see `get_previews` and `view_previews` in [`getSpatialData`](https://github.com/16EAGLE/getSpatialData), but have not yet thought of including something like this in `basemaps`.

> I  have written code that returns such a basemap and have some code that queries the data. I am sure you are incredibly busy but if you ever thought you might like to extend Mapbox's capabilities to include data never at cost, then I'd be happy to send that code along if you thought it might be helpful.

I am always happy about contributions, though I am not sure I will have time to implement a new feature like that soon. But I am certainly interested in your solution. If you like to contribute, also feel free to add such a functionality through a PR!
