### ISSUE TITLE
Support for specifying tile zoom level?

### ISSUE THREAD

**Issue by stevenbedrick** [16EAGLE/basemaps#15]
Hello! First, thanks so much for this library, it is a real pleasure to use. So my question is about whether it is possible to specify the zoom level (along with the map service and map type). Many map services offer tiles at a variety of zoom levels, but I can't see where or how to specify that using `basemaps`- looking at the code, it appears to be using whatever `slippymath::bbox_to_tile_grid()` uses as a default for the given map service (see [here](https://github.com/16EAGLE/basemaps/blob/18f6196bd09ee1cf78644426796321b9bdb9c512/R/internal.R#L134)). Am I missing an option somewhere?

**Comment by 16EAGLE** [comment]
Thanks for solving this by adding that feature through a PR! 

For the record, one can now run something like

```R
basemap_magick(ext, custom_zoom = 3) #or
basemap_magick(ext, custom_zoom = 6) #and so on
```
or similar to change zoom level/map detail, overruling `map_res`.

**Comment by stevenbedrick** [comment]
Oh cool, that's definitely better nomenclature- thanks!
