### ISSUE TITLE
plotRGB throws color intensity bug

### ISSUE THREAD

**Issue by jebyrnes** [16EAGLE/basemaps#25]
Working on a piece where

```{r plot-rgb-image, eval = FALSE}
plotRGB(landsat_colors_1230,
        r = 3, g = 2, b = 1)
```
throws the error

```
Error in grDevices::rgb(RGB[, 1], RGB[, 2], RGB[, 3], alpha = out$alpha,  : 
  color intensity 1.00153, not in [0,1]
```

But if I rescale it by the max value of those three channels

```
plotRGB(landsat_colors_1230 * 255/51097,
        r = 3, g = 2, b = 1)
```

everything is fine. Not sure what's going on here.

**Comment by 16EAGLE** [comment]
Thanks for reporting that bug. I cannot reproduce it with your example. In case you have a minimal reproducible example, please provide it.
