### ISSUE TITLE
basemaps removed from CRAN

### ISSUE THREAD

**Issue by xiaofanliang** [16EAGLE/basemaps#27]
Hi, 

I am using `basemaps` in my class materials. I have loved this package so far and it makes integrating basemaps into `tmap` workflow a lot easier. 

However, today I found out that `basemaps` cannot be installed with R CRAN anymore [https://cran.r-project.org/web/packages/basemaps/index.html](https://cran.r-project.org/web/packages/basemaps/index.html). The development version still works, though others issues exist [https://github.com/16EAGLE/basemaps/issues/26](https://github.com/16EAGLE/basemaps/issues/26). 

Does it mean the package is abandoned? Is it in the process of updating? If it is the former, I will remove it from my class materials in the future. 

Thanks.

**Comment by 16EAGLE** [comment]
Hi,

the package will be back on CRAN soon. I was busy with other work and could not maintain the package for a while. Glad to read you are using the package for teaching. 

The current `basemaps` version on GitHub should work fine, with some changes such as `osm_stamen` now requiring a map token from Stadia Maps. For your class, you can just use the GitHub version using `remotes::install_github("16eagle/basemaps")` until CRAN is updated.

Best

**Comment by 16EAGLE** [comment]
`basemaps` is back on CRAN, closing this issue.
