### ISSUE TITLE
Why `Using geom_tile() with maxpixels = 5e+05.`

### ISSUE THREAD

**Issue by Rafnuss** [16EAGLE/basemaps#29]
Hi @16EAGLE ,
Thanks a lot for your packages!
Using `moveVis`, I ended up getting this message:  https://github.com/16EAGLE/basemaps/blob/203e9643c3d222ecdfa68b4ea5d4ae01d378bf7b/R/plot.R#L89-L90 that I don't really understand. 
I'm using map_service = "mapbox", map_type = "satellite" in `frames_sptial`, so not sure where the `na` are coming from. But in anycase I don't see the link between NA and the error message. 
It ended up being quite annoying to have this message so many time during `animate_frames()`. Can we remove it?

**Comment by andrewdigby** [comment]
I agree. Does anyone know how to suppress it? It makes my Markdown unreadable!
Thanks.

**Comment by 16EAGLE** [comment]
Thanks for pointing out that this message added unnecessary verbosity. I don't remember really why I added it in the first place to be honest. 

I removed the message.
