### ISSUE TITLE
Stamen Watercolor tiles return 404 error

### ISSUE THREAD

**Issue by pushing-boulders** [16EAGLE/basemaps#30]
Hello.  Thank you for this great library.  I am working with someone who is trying to utilize the [Stamen Watercolor tiles from Stadia Maps](https://docs.stadiamaps.com/map-styles/stamen-watercolor/#__tabbed_1_1) with moveVis, but is receiving a 404 error.  Other Stamen and Stadia tiles work as expected.

My guess is that the tiles were previously served as .PNG format, however, they are now only available in .JPG.

Here is the XYZ URL:  `https://tiles.stadiamaps.com/tiles/stamen_watercolor/{z}/{x}/{y}.jpg`

Is it possible to make the appropriate adjustments to handle this different extension for Stamen Watercolor?

I don't know much R on my end, but I will give it a shot, too.

Thank you for your help.

**Comment by 16EAGLE** [comment]
Thank you. This got fixed by yourself with PR #31 :slightly_smiling_face:  Closing.
