### ISSUE TITLE
Higher resolution 

### ISSUE THREAD

**Issue by dominicroye** [16EAGLE/basemaps#5]
Hi, 

Your package is great. But I have noticed that the resolution is low with only 72 dpi which is in many cases not enough when I work with high-resolution data.  Is there a way to get 300 dpi? 

```
library(basemaps)
data(ext)
basemap_magick(ext, map_service = "carto",
               map_type = "dark_no_labels",
               map_res = 1)
```

Best,

Dominic

**Comment by 16EAGLE** [comment]
Hi,

for writing downloaded map tiles as PNGs in the first place, `basemaps` internally uses `magick::write()`, maintaining the original tile dpi. After mosaicing, cropping and converting to GeoTIFF in the process, `basemaps` uses `png::writePNG()` with defaults to convert the GeoTIFF mosaic back to PNG. This apparently results in a default dpi of 72. I added the option to pass the `dpi` argument down to `png::writePNG()` form any `basemap*` function, e.g. like this:

```R
basemap_magick(ext, map_service = "carto", map_type = "dark_no_labels", map_res = 1, dpi = 300)
```
or

```R
basemap_png(ext, map_service = "carto", map_type = "dark_no_labels", map_res = 1, dpi = 300)
```

Does this solve your issue?

**Comment by 16EAGLE** [comment]
Please reopen if this did not solve the issue.
